# Multiple linear regression

## Import the relevant libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

## Load the data

In [2]:
data = pd.read_csv('1.02. Multiple linear regression.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

## Create the multiple linear regression

### Declare the dependent and independent variables

In [3]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

### Regression itself

In [4]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [5]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [6]:
reg.intercept_

0.29603261264909486

### Calculating the R-squared

the R-squared is universal measure to evaluate how well linear regressions fare and compare

In [7]:
reg.score(x,y)

0.4066811952814285

### Formula for Adjusted R^2

$n$: 84 (the number of observations)

$p$: 2 (the number of predictors)

$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$


The Adjusted R-squared steps on the R-squared and adjusts for the number of variables included in the model.

In [8]:
x.shape

(84, 2)

In [9]:
r2 = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]

adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.39203134825134023

So $R^2_{adj.} < R^2$, therefore one or more of the predictors have little or no explanatory power and if we can identify which one and remove it, we could further simplify our model.

## How to detect the variables which are useless in a model?

# Feature Selection

Feature selection simplifies models, improves speed and prevents a series of unwanted issues arising from having too many features.

F-regression method creates simple linear regressions of each feature and the dependent variable:

1. predict GPA from SAT
2. predict GPA from Rand 1,2,3

In [10]:
from sklearn.feature_selection import f_regression

In [11]:
f_regression(x, y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

The first array contains the F-statistics for each regression while the second the corresponding p values.

In [12]:
p_values = f_regression(x, y)[1]

Let's round the numbers to only three digits after the dot:

In [13]:
p_values.round(3)

array([0.   , 0.676])

The first one refers to the first column of x (SAT), while the second one to the second (Rand).

**Note:** these are the univariate p-values reached from simple linear models. They do not reflect the interconnection of the features in our multiple linear regression.

# Creating a summary table

In [15]:
reg_summary = pd.DataFrame(data=x.columns.values, columns=['features'])
reg_summary

features
0         SAT
1  Rand 1,2,3

In [16]:
reg_summary['coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)

In [17]:
reg_summary

features  coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

P-values are one of the best ways to determine if a variable is redundant, but they provide no information about haw useful a variable is.